apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-frontend-config
  namespace: saviaup-dev
  labels:
    app.kubernetes.io/name: admin-frontend
    app.kubernetes.io/part-of: saviaup
    environment: dev
data:
  API_URL: "https://dev.api.admin.saviaup.com"
