apiVersion: v1
kind: Secret
metadata:
  name: admin-frontend-secret
  namespace: saviaup-dev
  labels:
    app.kubernetes.io/name: admin-frontend
    app.kubernetes.io/part-of: saviaup
    environment: dev
type: Opaque
stringData:
  APP_ENV: "dev"
