apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: saviaup-dev
  labels:
    app.kubernetes.io/part-of: saviaup
    environment: dev
type: kubernetes.io/dockerconfigjson
# NOTA: Para generar este secret mediante comando ejecutar:
# kubectl create secret docker-registry ghcr-secret \
#   --docker-server=ghcr.io \
#   --docker-username=<TU_GITHUB_USER> \
#   --docker-password=<TU_GITHUB_PAT_TOKEN> \
#   --namespace=saviaup-dev
stringData:
  .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"CHANGE_ME_GITHUB_USER","password":"CHANGE_ME_GITHUB_PAT","auth":"CHANGE_ME"}}}'
