apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-frontend-config
  namespace: saviaup-qa
  labels:
    app.kubernetes.io/name: admin-frontend
    app.kubernetes.io/part-of: saviaup
    environment: qa
data:
  API_URL: "https://qa.api.admin.saviaup.com"
