apiVersion: v1
kind: Secret
metadata:
  name: admin-frontend-secret
  namespace: saviaup-prod
  labels:
    app.kubernetes.io/name: admin-frontend
    app.kubernetes.io/part-of: saviaup
    environment: prod
type: Opaque
stringData:
  APP_ENV: "production"
