apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: saviaup-qa
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: saviaup
    environment: qa
type: Opaque
stringData:
  ConnectionStrings__PlatformDatabase: "${{Qa_PlatformDatabase__ConnectionString}}"
  ConnectionStrings__ApplicationDatabase: "${{Qa_ApplicationDatabase__ConnectionString}}"
  Jwt__SigningKey: "${{Qa_Jwt__SigningKey}}"
