apiVersion: v1
kind: Secret
metadata:
  name: frontend-menu-secret
  namespace: saviaup-qa
  labels:
    app.kubernetes.io/name: frontend-menu
    app.kubernetes.io/part-of: saviaup
    environment: qa
type: Opaque
stringData:
  APP_ENV: "qa"
