apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saviaup-prod

resources:
  - backend/backend-manifest.yaml
  - backend/secret.yaml
  - frontend/frontend-manifest.yaml
  - frontend/secret.yaml
  - frontend-menu/frontend-menu-manifest.yaml
  - frontend-menu/secret.yaml
  - admin-backend/admin-backend-manifest.yaml
  - admin-backend/secret.yaml
  - admin-frontend/admin-frontend-manifest.yaml
  - admin-frontend/secret.yaml
  - downloads/print-agent-downloads.yaml
  - ingress.yaml
  - ghcr-secret.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: saviaup
      environment: prod
