apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saviaup-prod

resources:
  - backend/configmap.yaml
  - backend/secret.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/configmap.yaml
  - frontend/secret.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - admin-backend/configmap.yaml
  - admin-backend/secret.yaml
  - admin-backend/deployment.yaml
  - admin-backend/service.yaml
  - admin-frontend/configmap.yaml
  - admin-frontend/secret.yaml
  - admin-frontend/deployment.yaml
  - admin-frontend/service.yaml
  - ingress.yaml
  - ghcr-secret.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: saviaup
      environment: prod
