apiVersion: v1
kind: Secret
metadata:
  name: admin-backend-secret
  namespace: saviaup-qa
  labels:
    app.kubernetes.io/name: admin-backend
    app.kubernetes.io/part-of: saviaup
    environment: qa
type: Opaque
stringData:
  ConnectionStrings__AdminDatabase: "${{Qa_AdminDatabase__ConnectionString}}"
  ConnectionStrings__PlatformDatabase: "${{Qa_PlatformDatabase__ConnectionString}}"
  ConnectionStrings__ApplicationDatabase: "${{Qa_ApplicationDatabase__ConnectionString}}"
  Jwt__SigningKey: "${{Qa_Admin_Jwt__SigningKey}}"
