apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: saviaup-prod
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: saviaup
    environment: prod
type: Opaque
stringData:
  ConnectionStrings__PlatformDatabase: "${{Prod_PlatformDatabase__ConnectionString}}"
  ConnectionStrings__ApplicationDatabase: "${{Prod_ApplicationDatabase__ConnectionString}}"
  Jwt__SigningKey: "${{Prod_Jwt__SigningKey}}"
  