apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: saviaup-dev
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: saviaup
    environment: dev
data:
  API_URL: "https://dev.api.saviaup.com"
  SIGNALR_URL: "https://dev.api.saviaup.com"
