apiVersion: v1
kind: Secret
metadata:
  name: admin-backend-secret
  namespace: saviaup-prod
  labels:
    app.kubernetes.io/name: admin-backend
    app.kubernetes.io/part-of: saviaup
    environment: prod
type: Opaque
stringData:
  ConnectionStrings__AdminDatabase: "${{Prod_AdminDatabase__ConnectionString}}"
  ConnectionStrings__PlatformDatabase: "${{Prod_PlatformDatabase__ConnectionString}}"
  ConnectionStrings__ApplicationDatabase: "${{Prod_ApplicationDatabase__ConnectionString}}"
  Jwt__SigningKey: "${{Prod_Admin_Jwt__SigningKey}}"
