apiVersion: v1
kind: Secret
metadata:
  name: admin-backend-secret
  namespace: saviaup-dev
  labels:
    app.kubernetes.io/name: admin-backend
    app.kubernetes.io/part-of: saviaup
    environment: dev
type: Opaque
stringData:
  ConnectionStrings__AdminDatabase: "${{Dev_AdminDatabase__ConnectionString}}"
  ConnectionStrings__PlatformDatabase: "${{Dev_PlatformDatabase__ConnectionString}}"
  ConnectionStrings__ApplicationDatabase: "${{Dev_ApplicationDatabase__ConnectionString}}"
  Jwt__SigningKey: "${{Dev_Admin_Jwt__SigningKey}}"
