apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saviaup-ingress
  namespace: saviaup-qa
  labels:
    app.kubernetes.io/part-of: saviaup
    environment: qa
  annotations:
    ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - qa.saviaup.com
        - qa.admin.saviaup.com
      secretName: saviaup-tls
  rules:
    - host: qa.saviaup.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: qa.admin.saviaup.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-frontend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saviaup-api-ingress
  namespace: saviaup-qa
  labels:
    app.kubernetes.io/part-of: saviaup
    environment: qa
  annotations:
    ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - qa-api.saviaup.com
        - qa-api-admin.saviaup.com
      secretName: saviaup-tls
  rules:
    - host: qa-api.saviaup.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  number: 8080
    - host: qa-api-admin.saviaup.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: admin-backend
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: print-agent-downloads-ingress
  namespace: saviaup-qa
  labels:
    app.kubernetes.io/part-of: saviaup
    environment: qa
  annotations:
    ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - qa-downloads.saviaup.com
      secretName: saviaup-tls
  rules:
    - host: qa-downloads.saviaup.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: print-agent-downloads
                port:
                  number: 80
