apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saviaup-ingress
  namespace: saviaup-qa
  labels:
    app.kubernetes.io/part-of: saviaup
    environment: qa
  annotations:
    ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - qa.saviaup.com
        - qa.api.saviaup.com
        - qa.admin.saviaup.com
        - qa.api.admin.saviaup.com
      secretName: saviaup-qa-tls
  rules:
    # 1. Frontend Web QA
    - host: qa.saviaup.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

    # 2. Backend API QA
    - host: qa.api.saviaup.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080

    # 3. Admin Frontend QA
    - host: qa.admin.saviaup.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-frontend
                port:
                  number: 80

    # 4. Admin Backend API QA
    - host: qa.api.admin.saviaup.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-backend
                port:
                  number: 8080
